---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifconfig
  namespace: ifconfig
  labels:
    app: ifconfig.me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifconfig.me
  template:
    metadata:
      labels:
        app: ifconfig.me
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ifconfig
        image: patrickfmarques/ifconfig.me:latest
        args: ["--port", "8080"]
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 10000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: OTEL_SERVICE_NAME
          value: ifconfig
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.observability.svc:4318
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 30
          terminationGracePeriodSeconds: 1
        readinessProbe:
          httpGet:
            path: /ip
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
